### ISSUE TITLE
Implement contract channel calls

### ISSUE THREAD

**Issue by jtremback** [althea-mesh/guac_rs#20]
Right now Gauc_rs has testing for the payment channel workflow but does not include any actual calls to update balances throughout the actual channel creation and orchestration code. 

meeting with Ben on Friday about how exactly to structure the calls. 

deadline:10/24/2018

**Comment by mpapierski** [comment]
Couple of notes after the call with Ben:

- Occasional polling of balance on the network might be be useful way to detect conditions that occur without our knowledge (Example scenario: we're rebooting/or we lost connection to outside world while an attempt is made to close the channel).
- We should take network errors into considerating when doing calls. Any time calling the network we should make sure the connection still exists, and if it doesn't we should retry it.
- Polling for confirmations after a contract call is made with a variable required confirmations. Should be a hardcoded constant, but there shouldn't be a problem with making it a configurable variable.
- Completely forget (or maybe even delete?) guac_http, as there is no immediate need for that.
