### ISSUE TITLE
Implement pluggalbe transports as specced in documentated traits

### ISSUE THREAD

**Issue by jkilpatr** [althea-mesh/guac_rs#36]
https://github.com/althea-mesh/guac_rs/pull/35
specs out pluggable transport traits, the network code for gauc should be re-factored to implement these.

deadline: 10/9/18

**Comment by mpapierski** [comment]
I'm reopening as it was closed accidentally when I closed #35 to not interfere with @jtremback work

**Comment by jkilpatr** [comment]
I'm going to try and break this down into some smaller issues.
